[package]
name = "rayt-rs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
env_logger = "0.11.8"
indicatif = "0.18.0"
log = "0.4.27"
toml = "0.9.5"

[dependencies.glam]
version = "0.30.5"
features = ["serde"]

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
